language: vi_spacy_model
pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    features:
      - - low
        - title
        - upper
      - - bias
        - low
        - prefix5
        - prefix2
        - suffix5
        - suffix3
        - suffix2
        - upper
        - title
        - digit
        - pattern
      - - low
        - title
        - upper
  - name: EntitySynonymMapper
  - name: SklearnIntentClassifier

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy
